#!/usr/bin/env bash
set -euo pipefail

files=(
  "apps/desktop/ui/app.js"
  "apps/desktop/ui/modules/app-core.js"
  "apps/desktop/ui/modules/ocr-controller.js"
  "apps/desktop/ui/modules/upgrade-ui-controller.js"
  "apps/desktop/ui/modules/upgrade-scorer-config-view.js"
  "apps/desktop/ui/modules/upgrade-weight-inputs-view.js"
  "apps/desktop/ui/modules/upgrade-buff-slots-view.js"
  "apps/desktop/ui/modules/upgrade-label-formatters.js"
  "apps/desktop/ui/modules/upgrade-score-controller.js"
  "apps/desktop/ui/modules/target-score-controller.js"
  "apps/desktop/ui/modules/state-bootstrap.js"
  "apps/desktop/ui/modules/policy-controller.js"
  "apps/desktop/ui/modules/policy-view.js"
  "apps/desktop/ui/modules/policy-actions.js"
  "apps/desktop/ui/modules/mode-flow-controller.js"
  "apps/desktop/ui/modules/scorer-state-controller.js"
  "apps/desktop/ui/modules/app-state-factory.js"
  "apps/desktop/ui/modules/dom-cache.js"
  "apps/desktop/ui/modules/scorer-config-copy.js"
  "apps/desktop/ui/modules/scorer-payload-builder.js"
  "apps/desktop/ui/modules/help-tooltip.js"
  "apps/desktop/ui/modules/app-init-controller.js"
  "apps/desktop/ui/modules/presets-controller.js"
  "apps/desktop/ui/modules/presets-model.js"
  "apps/desktop/ui/modules/presets-view-controller.js"
  "apps/desktop/ui/modules/presets-mutations.js"
  "apps/desktop/ui/modules/presets-selection-actions.js"
  "apps/desktop/ui/modules/presets-button-loading.js"
  "apps/desktop/ui/modules/presets-save-actions.js"
  "apps/desktop/ui/modules/presets-delete-actions.js"
  "apps/desktop/ui/modules/reroll-controller.js"
  "apps/desktop/ui/modules/reroll-policy-controller.js"
  "apps/desktop/ui/modules/reroll-view-controller.js"
  "apps/desktop/ui/modules/reroll-view-meta.js"
  "apps/desktop/ui/modules/reroll-view-output.js"
  "apps/desktop/ui/modules/reroll-view-slots.js"
  "apps/desktop/ui/modules/event-handlers-controller.js"
  "apps/desktop/ui/modules/event-handlers-ocr-tabs.js"
  "apps/desktop/ui/modules/event-handlers-upgrade.js"
  "apps/desktop/ui/modules/event-handlers-reroll.js"
  "apps/desktop/ui/modules/constants.js"
  "apps/desktop/ui/modules/utils.js"
  "apps/desktop/ui/modules/tauri-api.js"
)

for file in "${files[@]}"; do
  echo "node --check $file"
  node --check "$file"
done

echo "UI syntax checks passed."
